# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aceb13a27564413b7679b6a498f6e07b502ace21fc0ce5f876c3c7ae5c37f059cf493ca743875324405093e6b5bf57c24ac66b78ca3a9b612926ea203e4e7ab6

test:
  secret_key_base: e51179ea5c2af28d7c6bc71c2a94ab863474656ebac2ae77e9b8be75d5865364483acd7a281b3df794e71c570f60d77a3cbb72be2821873624eb9549f332d3f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
